MODEL:
  DEVICE: 'cuda'
  WEIGHTS: "/cfs/cfs-4a8cd28be/mmatch/infguo/weights/bua-caffe-frcn-r101_with_attributes.pth"
  META_ARCHITECTURE: "GeneralizedBUARCNN"
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  ANCHOR_GENERATOR:
    SIZES: [[4, 8, 16, 32]]
  PROPOSAL_GENERATOR:
    NAME: "BUARPN"
    MIN_SIZE: 16
  BUA:
    ATTRIBUTE_ON: True
    EXTRACT_FEATS: True
    RPN:
      CONV_OUT_CHANNELS: 512
    EXTRACTOR:
      MODE: 2
      MIN_BOXES: 5
      MAX_BOXES: 45
      CONF_THRESH: 0.4
    ATTRIBUTE:
      NUM_CLASSES: 401
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res4"]
    NORM: "BN"
    RES5_DILATION: 2
  BACKBONE:
    NAME: "build_bua_resnet_backbone"
    FREEZE_AT: 3
  RPN:
    HEAD_NAME: "StandardBUARPNHead"
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 300
    PRE_NMS_TOPK_TEST: 6000
    BATCH_SIZE_PER_IMAGE: 64
  ROI_HEADS:
    NAME: "BUACaffeRes5ROIHeads"
    BATCH_SIZE_PER_IMAGE: 64
    SCORE_THRESH_TEST: -1.0
    NMS_THRESH_TEST: 0.3
    POSITIVE_FRACTION: 0.5
    NUM_CLASSES: 1601
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIPool"
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000

